pub mod nv_memory;

pub enum NvItemsIds {
    ExtAddr,
    BootCounter,
    StartupOption,
    StartDelay,
    NIB,
    DeviceList,
    AddrMgr,
    PollRate,
    QueuedPollRate,
    ResponsePollRate,
    RejoinPollRate,
    DataRetries,
    PollFailureRetries ,
    StackProfile ,
    IndirectMsgTimeout,
    RouteExpiryTime,
    ExtendedPanId,
    BcastRetries,
    PassiveAckTimeout,
    BcastDeliveryTime,
    NwkMode ,
    ConcentratorEnable ,
    ConcentratorDiscovery ,
    ConcentratorRadius ,
    ConcentratorRc ,
    NwkMgrMode ,
    SrcRtgExpiryTime ,
    RouteDiscoveryTime ,
    NwkActiveKeyInfo ,
    NwkAlternKeyInfo,
    RouterOffAssocCleanup,
    NwkLeaveReqAllowed ,
    NwkChildAgeEnable,
    DeviceListKaTimeout ,
    BindingTable ,
    GroupTable,
    ApsFrameRetries,
    ApsAckWaitDuration,
    ApsAckWaitMultiplier ,
    BindingTime ,
    ApsUseExtPanid,
    ApsUseInsecureJoin,
    CommissionedNwkAddr,
    ApsNonmemberRadius,
    ApsLinkKeyTable,
    ApsDuprejTimeoutInc,
    ApsDuprejTimeoutCount,
    ApsDuprejTableSize ,
    DiagnosticStats,
    BdbNodeIsonaNetwork ,
    SecurityLevel,
    PreCfgKey,
    PrecfgkeysEnable ,
    SecurityMode ,
    SecurePermitJoin ,
    ApsLinkKeyType,
    ApsAllowR19Security,
    ImplicitCertificate ,
    DevicePrivateKey,
    CaPublicKey,
    KeMaxDevices,
    UseDefaultTclk,
    RngCounter ,
    RandomSeed,
    TrustcenterAddr ,
    LegacyNwkSecMaterialTableStart ,// Valid for <= Z-Stack 3.0.x
    ExNwkSecMaterialTable ,// Valid for >= Z-Stack 3.x.0
    UserDesc ,
    NwkKey,
    PanId ,
    ChanList ,
    LeaveCtrl ,
    ScanDuration ,
    LogicalType ,
    NwkmgrMinTx ,
    NwkmgrAddr ,
    ZdoDirectCb ,
    SceneTable,
    MinFreeNwkAddr ,
    MaxFreeNwkAddr,
    MinFreeGrpId ,
    MaxFreeGrpId,
    MinGrpIds,
    MaxGrpIds ,
    OtaBlockReqDelay ,
    SapiEndpoint,
    SasShortAddr,
    SasExtPanid,
    SasPanid ,
    SasChannelMask ,
    SasProtocolVer ,
    SasStackProfile,
    SasStartupCtrl ,
    SasTcAddr ,
    SasTcMasterKey ,
    SasNwkKey ,
    SasUseInsecJoin ,
    SasPrecfgLinkKey ,
    SasNwkKeySeqNum,
    SasNwkKeyType ,
    SasNwkMgrAddr ,
    SasCurrTcMasterKey ,
    SasCurrNwkKey ,
    SasCurrPrecfgLinkKey ,
    TclkSeed,
    LegacyTclkTableStart12 , // Keep it for Legacy 1.2 stack
    LegacyTclkTableStart, // Valid for <= Z-Stack 3.0.x
    ExTclkTable, // Valid for >= Z-Stack 3.0.x
    ApsLinkKeyDataStart,
    ApsLinkKeyDataEnd,
    DuplicateBindingTable,
    DuplicateDeviceList,
    DuplicateDeviceListKaTimeout,
    ZnpHasConfiguredZstack1,
    ZnpHasConfiguredZstack3,
    ZcdNvExApsKeyDataTable ,
    ZcdNvExAddrmgr 
}
