pub mod entries;
pub mod nv_memory;

#[derive(Debug, PartialEq, Clone, Copy)]
pub enum NvItemId {
    ExtAddr,
    BootCounter,
    StartupOption,
    StartDelay,
    NIB,
    DeviceList,
    AddrMgr,
    PollRate,
    QueuedPollRate,
    ResponsePollRate,
    RejoinPollRate,
    DataRetries,
    PollFailureRetries,
    StackProfile,
    IndirectMsgTimeout,
    RouteExpiryTime,
    ExtendedPanId,
    BcastRetries,
    PassiveAckTimeout,
    BcastDeliveryTime,
    NwkMode,
    ConcentratorEnable,
    ConcentratorDiscovery,
    ConcentratorRadius,
    ConcentratorRc,
    NwkMgrMode,
    SrcRtgExpiryTime,
    RouteDiscoveryTime,
    NwkActiveKeyInfo,
    NwkAlternKeyInfo,
    RouterOffAssocCleanup,
    NwkLeaveReqAllowed,
    NwkChildAgeEnable,
    DeviceListKaTimeout,
    BindingTable,
    GroupTable,
    ApsFrameRetries,
    ApsAckWaitDuration,
    ApsAckWaitMultiplier,
    BindingTime,
    ApsUseExtPanid,
    ApsUseInsecureJoin,
    CommissionedNwkAddr,
    ApsNonmemberRadius,
    ApsLinkKeyTable,
    ApsDuprejTimeoutInc,
    ApsDuprejTimeoutCount,
    ApsDuprejTableSize,
    DiagnosticStats,
    BdbNodeIsonaNetwork,
    SecurityLevel,
    PreCfgKey,
    PrecfgkeysEnable,
    SecurityMode,
    SecurePermitJoin,
    ApsLinkKeyType,
    ApsAllowR19Security,
    ImplicitCertificate,
    DevicePrivateKey,
    CaPublicKey,
    KeMaxDevices,
    UseDefaultTclk,
    RngCounter,
    RandomSeed,
    TrustcenterAddr,
    LegacyNwkSecMaterialTableStart, // Valid for <= Z-Stack 3.0.x
    ExNwkSecMaterialTable,          // Valid for >= Z-Stack 3.x.0
    UserDesc,
    NwkKey,
    PanId,
    ChanList,
    LeaveCtrl,
    ScanDuration,
    LogicalType,
    NwkmgrMinTx,
    NwkmgrAddr,
    ZdoDirectCb,
    SceneTable,
    MinFreeNwkAddr,
    MaxFreeNwkAddr,
    MinFreeGrpId,
    MaxFreeGrpId,
    MinGrpIds,
    MaxGrpIds,
    OtaBlockReqDelay,
    SapiEndpoint,
    SasShortAddr,
    SasExtPanid,
    SasPanid,
    SasChannelMask,
    SasProtocolVer,
    SasStackProfile,
    SasStartupCtrl,
    SasTcAddr,
    SasTcMasterKey,
    SasNwkKey,
    SasUseInsecJoin,
    SasPrecfgLinkKey,
    SasNwkKeySeqNum,
    SasNwkKeyType,
    SasNwkMgrAddr,
    SasCurrTcMasterKey,
    SasCurrNwkKey,
    SasCurrPrecfgLinkKey,
    TclkSeed,
    LegacyTclkTableStart12, // Keep it for Legacy 1.2 stack
    LegacyTclkTableStart,   // Valid for <= Z-Stack 3.0.x
    ExTclkTable,            // Valid for >= Z-Stack 3.0.x
    ApsLinkKeyDataStart,
    ApsLinkKeyDataEnd,
    DuplicateBindingTable,
    DuplicateDeviceList,
    DuplicateDeviceListKaTimeout,
    ZnpHasConfiguredZstack1,
    ZnpHasConfiguredZstack3,
    ZcdNvExApsKeyDataTable,
    ZcdNvExAddrmgr,
}

impl Into<u16> for NvItemId {
    fn into(self) -> u16 {
        match self {
            NvItemId::ExtAddr => 1,
            NvItemId::BootCounter => 2,
            NvItemId::StartupOption => 3,
            NvItemId::StartDelay => 4,
            NvItemId::NIB => 33,
            NvItemId::DeviceList => 34,
            NvItemId::AddrMgr => 35,
            NvItemId::PollRate => 36,
            NvItemId::QueuedPollRate => 37,
            NvItemId::ResponsePollRate => 38,
            NvItemId::RejoinPollRate => 39,
            NvItemId::DataRetries => 40,
            NvItemId::PollFailureRetries => 41,
            NvItemId::StackProfile => 42,
            NvItemId::IndirectMsgTimeout => 43,
            NvItemId::RouteExpiryTime => 44,
            NvItemId::ExtendedPanId => 45,
            NvItemId::BcastRetries => 46,
            NvItemId::PassiveAckTimeout => 47,
            NvItemId::BcastDeliveryTime => 48,
            NvItemId::NwkMode => 49,
            NvItemId::ConcentratorEnable => 50,
            NvItemId::ConcentratorDiscovery => 51,
            NvItemId::ConcentratorRadius => 52,
            NvItemId::ConcentratorRc => 54,
            NvItemId::NwkMgrMode => 55,
            NvItemId::SrcRtgExpiryTime => 56,
            NvItemId::RouteDiscoveryTime => 57,
            NvItemId::NwkActiveKeyInfo => 58,
            NvItemId::NwkAlternKeyInfo => 59,
            NvItemId::RouterOffAssocCleanup => 60,
            NvItemId::NwkLeaveReqAllowed => 61,
            NvItemId::NwkChildAgeEnable => 62,
            NvItemId::DeviceListKaTimeout => 63,
            NvItemId::BindingTable => 65,
            NvItemId::GroupTable => 66,
            NvItemId::ApsFrameRetries => 67,
            NvItemId::ApsAckWaitDuration => 68,
            NvItemId::ApsAckWaitMultiplier => 69,
            NvItemId::BindingTime => 70,
            NvItemId::ApsUseExtPanid => 71,
            NvItemId::ApsUseInsecureJoin => 72,
            NvItemId::CommissionedNwkAddr => 73,
            NvItemId::ApsNonmemberRadius => 75,
            NvItemId::ApsLinkKeyTable => 76,
            NvItemId::ApsDuprejTimeoutInc => 77,
            NvItemId::ApsDuprejTimeoutCount => 78,
            NvItemId::ApsDuprejTableSize => 79,
            NvItemId::DiagnosticStats => 80,
            NvItemId::BdbNodeIsonaNetwork => 85,
            NvItemId::SecurityLevel => 97,
            NvItemId::PreCfgKey => 98,
            NvItemId::PrecfgkeysEnable => 99,
            NvItemId::SecurityMode => 100,
            NvItemId::SecurePermitJoin => 101,
            NvItemId::ApsLinkKeyType => 102,
            NvItemId::ApsAllowR19Security => 103,
            NvItemId::ImplicitCertificate => 105,
            NvItemId::DevicePrivateKey => 106,
            NvItemId::CaPublicKey => 107,
            NvItemId::KeMaxDevices => 108,
            NvItemId::UseDefaultTclk => 109,
            NvItemId::RngCounter => 111,
            NvItemId::RandomSeed => 112,
            NvItemId::TrustcenterAddr => 113,
            NvItemId::LegacyNwkSecMaterialTableStart => 117,
            NvItemId::ExNwkSecMaterialTable => 7,
            NvItemId::UserDesc => 129,
            NvItemId::NwkKey => 130,
            NvItemId::PanId => 131,
            NvItemId::ChanList => 132,
            NvItemId::LeaveCtrl => 133,
            NvItemId::ScanDuration => 134,
            NvItemId::LogicalType => 135,
            NvItemId::NwkmgrMinTx => 136,
            NvItemId::NwkmgrAddr => 137,
            NvItemId::ZdoDirectCb => 143,
            NvItemId::SceneTable => 145,
            NvItemId::MinFreeNwkAddr => 146,
            NvItemId::MaxFreeNwkAddr => 147,
            NvItemId::MinFreeGrpId => 148,
            NvItemId::MaxFreeGrpId => 149,
            NvItemId::MinGrpIds => 150,
            NvItemId::MaxGrpIds => 151,
            NvItemId::OtaBlockReqDelay => 152,
            NvItemId::SapiEndpoint => 161,
            NvItemId::SasShortAddr => 177,
            NvItemId::SasExtPanid => 178,
            NvItemId::SasPanid => 179,
            NvItemId::SasChannelMask => 180,
            NvItemId::SasProtocolVer => 181,
            NvItemId::SasStackProfile => 182,
            NvItemId::SasStartupCtrl => 183,
            NvItemId::SasTcAddr => 193,
            NvItemId::SasTcMasterKey => 194,
            NvItemId::SasNwkKey => 195,
            NvItemId::SasUseInsecJoin => 196,
            NvItemId::SasPrecfgLinkKey => 197,
            NvItemId::SasNwkKeySeqNum => 198,
            NvItemId::SasNwkKeyType => 199,
            NvItemId::SasNwkMgrAddr => 200,
            NvItemId::SasCurrTcMasterKey => 209,
            NvItemId::SasCurrNwkKey => 210,
            NvItemId::SasCurrPrecfgLinkKey => 211,
            NvItemId::TclkSeed => 257,
            NvItemId::LegacyTclkTableStart12 => 257,
            NvItemId::LegacyTclkTableStart => 273,
            NvItemId::ExTclkTable => 4,
            NvItemId::ApsLinkKeyDataStart => 513,
            NvItemId::ApsLinkKeyDataEnd => 767,
            NvItemId::DuplicateBindingTable => 768,
            NvItemId::DuplicateDeviceList => 769,
            NvItemId::DuplicateDeviceListKaTimeout => 770,
            NvItemId::ZnpHasConfiguredZstack1 => 3840,
            NvItemId::ZnpHasConfiguredZstack3 => 96,
            NvItemId::ZcdNvExApsKeyDataTable => 6,
            NvItemId::ZcdNvExAddrmgr => 1,
        }
    }
}

/*

export enum NvItemsIds {
    EXTADDR = 1,
    BOOTCOUNTER = 2,
    STARTUP_OPTION = 3,
    START_DELAY = 4,
    NIB = 33,
    DEVICE_LIST = 34,
    ADDRMGR = 35,
    POLL_RATE = 36,
    QUEUED_POLL_RATE = 37,
    RESPONSE_POLL_RATE = 38,
    REJOIN_POLL_RATE = 39,
    DATA_RETRIES = 40,
    POLL_FAILURE_RETRIES = 41,
    STACK_PROFILE = 42,
    INDIRECT_MSG_TIMEOUT = 43,
    ROUTE_EXPIRY_TIME = 44,
    EXTENDED_PAN_ID = 45,
    BCAST_RETRIES = 46,
    PASSIVE_ACK_TIMEOUT = 47,
    BCAST_DELIVERY_TIME = 48,
    NWK_MODE = 49,
    CONCENTRATOR_ENABLE = 50,
    CONCENTRATOR_DISCOVERY = 51,
    CONCENTRATOR_RADIUS = 52,
    CONCENTRATOR_RC = 54,
    NWK_MGR_MODE = 55,
    SRC_RTG_EXPIRY_TIME = 56,
    ROUTE_DISCOVERY_TIME = 57,
    NWK_ACTIVE_KEY_INFO = 58,
    NWK_ALTERN_KEY_INFO = 59,
    ROUTER_OFF_ASSOC_CLEANUP = 60,
    NWK_LEAVE_REQ_ALLOWED = 61,
    NWK_CHILD_AGE_ENABLE = 62,
    DEVICE_LIST_KA_TIMEOUT = 63,
    BINDING_TABLE = 65,
    GROUP_TABLE = 66,
    APS_FRAME_RETRIES = 67,
    APS_ACK_WAIT_DURATION = 68,
    APS_ACK_WAIT_MULTIPLIER = 69,
    BINDING_TIME = 70,
    APS_USE_EXT_PANID = 71,
    APS_USE_INSECURE_JOIN = 72,
    COMMISSIONED_NWK_ADDR = 73,
    APS_NONMEMBER_RADIUS = 75,
    APS_LINK_KEY_TABLE = 76,
    APS_DUPREJ_TIMEOUT_INC = 77,
    APS_DUPREJ_TIMEOUT_COUNT = 78,
    APS_DUPREJ_TABLE_SIZE = 79,
    DIAGNOSTIC_STATS = 80,
    BDBNODEISONANETWORK = 85,
    SECURITY_LEVEL = 97,
    PRECFGKEY = 98,
    PRECFGKEYS_ENABLE = 99,
    SECURITY_MODE = 100,
    SECURE_PERMIT_JOIN = 101,
    APS_LINK_KEY_TYPE = 102,
    APS_ALLOW_R19_SECURITY = 103,
    IMPLICIT_CERTIFICATE = 105,
    DEVICE_PRIVATE_KEY = 106,
    CA_PUBLIC_KEY = 107,
    KE_MAX_DEVICES = 108,
    USE_DEFAULT_TCLK = 109,
    RNG_COUNTER = 111,
    RANDOM_SEED = 112,
    TRUSTCENTER_ADDR = 113,
    LEGACY_NWK_SEC_MATERIAL_TABLE_START = 117, // Valid for <= Z-Stack 3.0.x
    EX_NWK_SEC_MATERIAL_TABLE = 7, // Valid for >= Z-Stack 3.x.0
    USERDESC = 129,
    NWKKEY = 130,
    PANID = 131,
    CHANLIST = 132,
    LEAVE_CTRL = 133,
    SCAN_DURATION = 134,
    LOGICAL_TYPE = 135,
    NWKMGR_MIN_TX = 136,
    NWKMGR_ADDR = 137,
    ZDO_DIRECT_CB = 143,
    SCENE_TABLE = 145,
    MIN_FREE_NWK_ADDR = 146,
    MAX_FREE_NWK_ADDR = 147,
    MIN_FREE_GRP_ID = 148,
    MAX_FREE_GRP_ID = 149,
    MIN_GRP_IDS = 150,
    MAX_GRP_IDS = 151,
    OTA_BLOCK_REQ_DELAY = 152,
    SAPI_ENDPOINT = 161,
    SAS_SHORT_ADDR = 177,
    SAS_EXT_PANID = 178,
    SAS_PANID = 179,
    SAS_CHANNEL_MASK = 180,
    SAS_PROTOCOL_VER = 181,
    SAS_STACK_PROFILE = 182,
    SAS_STARTUP_CTRL = 183,
    SAS_TC_ADDR = 193,
    SAS_TC_MASTER_KEY = 194,
    SAS_NWK_KEY = 195,
    SAS_USE_INSEC_JOIN = 196,
    SAS_PRECFG_LINK_KEY = 197,
    SAS_NWK_KEY_SEQ_NUM = 198,
    SAS_NWK_KEY_TYPE = 199,
    SAS_NWK_MGR_ADDR = 200,
    SAS_CURR_TC_MASTER_KEY = 209,
    SAS_CURR_NWK_KEY = 210,
    SAS_CURR_PRECFG_LINK_KEY = 211,
    TCLK_SEED = 257,
    // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
    LEGACY_TCLK_TABLE_START_12 = 257, // Keep it for Legacy 1.2 stack
    LEGACY_TCLK_TABLE_START = 273, // Valid for <= Z-Stack 3.0.x
    // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
    EX_TCLK_TABLE = 4, // Valid for >= Z-Stack 3.0.x
    APS_LINK_KEY_DATA_START = 513,
    APS_LINK_KEY_DATA_END = 767,
    DUPLICATE_BINDING_TABLE = 768,
    DUPLICATE_DEVICE_LIST = 769,
    DUPLICATE_DEVICE_LIST_KA_TIMEOUT = 770,
    ZNP_HAS_CONFIGURED_ZSTACK1 = 3840,
    ZNP_HAS_CONFIGURED_ZSTACK3 = 96,
    ZCD_NV_EX_APS_KEY_DATA_TABLE = 6,
    // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
    ZCD_NV_EX_ADDRMGR = 1,
}


*/
