pub mod entries;
pub mod nv_item;

#[derive(Debug, PartialEq, Clone, Copy)]
pub enum NvItemId {
    ExtAddr,
    BootCounter,
    StartupOption,
    StartDelay,
    NIB,
    DeviceList,
    AddrMgr,
    PollRate,
    QueuedPollRate,
    ResponsePollRate,
    RejoinPollRate,
    DataRetries,
    PollFailureRetries,
    StackProfile,
    IndirectMsgTimeout,
    RouteExpiryTime,
    ExtendedPanId,
    BcastRetries,
    PassiveAckTimeout,
    BcastDeliveryTime,
    NwkMode,
    ConcentratorEnable,
    ConcentratorDiscovery,
    ConcentratorRadius,
    ConcentratorRc,
    NwkMgrMode,
    SrcRtgExpiryTime,
    RouteDiscoveryTime,
    NwkActiveKeyInfo,
    NwkAlternKeyInfo,
    RouterOffAssocCleanup,
    NwkLeaveReqAllowed,
    NwkChildAgeEnable,
    DeviceListKaTimeout,
    BindingTable,
    GroupTable,
    ApsFrameRetries,
    ApsAckWaitDuration,
    ApsAckWaitMultiplier,
    BindingTime,
    ApsUseExtPanid,
    ApsUseInsecureJoin,
    CommissionedNwkAddr,
    ApsNonmemberRadius,
    ApsLinkKeyTable,
    ApsDuprejTimeoutInc,
    ApsDuprejTimeoutCount,
    ApsDuprejTableSize,
    DiagnosticStats,
    BdbNodeIsonaNetwork,
    SecurityLevel,
    PreCfgKey,
    PrecfgkeysEnable,
    SecurityMode,
    SecurePermitJoin,
    ApsLinkKeyType,
    ApsAllowR19Security,
    ImplicitCertificate,
    DevicePrivateKey,
    CaPublicKey,
    KeMaxDevices,
    UseDefaultTclk,
    RngCounter,
    RandomSeed,
    TrustcenterAddr,
    LegacyNwkSecMaterialTableStart, // Valid for <= Z-Stack 3.0.x
    ExNwkSecMaterialTable,          // Valid for >= Z-Stack 3.x.0
    UserDesc,
    NwkKey,
    PanId,
    ChanList,
    LeaveCtrl,
    ScanDuration,
    LogicalType,
    NwkmgrMinTx,
    NwkmgrAddr,
    ZdoDirectCb,
    SceneTable,
    MinFreeNwkAddr,
    MaxFreeNwkAddr,
    MinFreeGrpId,
    MaxFreeGrpId,
    MinGrpIds,
    MaxGrpIds,
    OtaBlockReqDelay,
    SapiEndpoint,
    SasShortAddr,
    SasExtPanid,
    SasPanid,
    SasChannelMask,
    SasProtocolVer,
    SasStackProfile,
    SasStartupCtrl,
    SasTcAddr,
    SasTcMasterKey,
    SasNwkKey,
    SasUseInsecJoin,
    SasPrecfgLinkKey,
    SasNwkKeySeqNum,
    SasNwkKeyType,
    SasNwkMgrAddr,
    SasCurrTcMasterKey,
    SasCurrNwkKey,
    SasCurrPrecfgLinkKey,
    TclkSeed,
    LegacyTclkTableStart12, // Keep it for Legacy 1.2 stack
    LegacyTclkTableStart,   // Valid for <= Z-Stack 3.0.x
    ExTclkTable,            // Valid for >= Z-Stack 3.0.x
    ApsLinkKeyDataStart,
    ApsLinkKeyDataEnd,
    DuplicateBindingTable,
    DuplicateDeviceList,
    DuplicateDeviceListKaTimeout,
    ZnpHasConfiguredZstack1,
    ZnpHasConfiguredZstack3,
    ZcdNvExApsKeyDataTable,
    ZcdNvExAddrmgr,
}

impl From<NvItemId> for u16 {
    fn from(item: NvItemId) -> u16 {
        match item {
            NvItemId::ExtAddr => 1,
            NvItemId::BootCounter => 2,
            NvItemId::StartupOption => 3,
            NvItemId::StartDelay => 4,
            NvItemId::NIB => 33,
            NvItemId::DeviceList => 34,
            NvItemId::AddrMgr => 35,
            NvItemId::PollRate => 36,
            NvItemId::QueuedPollRate => 37,
            NvItemId::ResponsePollRate => 38,
            NvItemId::RejoinPollRate => 39,
            NvItemId::DataRetries => 40,
            NvItemId::PollFailureRetries => 41,
            NvItemId::StackProfile => 42,
            NvItemId::IndirectMsgTimeout => 43,
            NvItemId::RouteExpiryTime => 44,
            NvItemId::ExtendedPanId => 45,
            NvItemId::BcastRetries => 46,
            NvItemId::PassiveAckTimeout => 47,
            NvItemId::BcastDeliveryTime => 48,
            NvItemId::NwkMode => 49,
            NvItemId::ConcentratorEnable => 50,
            NvItemId::ConcentratorDiscovery => 51,
            NvItemId::ConcentratorRadius => 52,
            NvItemId::ConcentratorRc => 54,
            NvItemId::NwkMgrMode => 55,
            NvItemId::SrcRtgExpiryTime => 56,
            NvItemId::RouteDiscoveryTime => 57,
            NvItemId::NwkActiveKeyInfo => 58,
            NvItemId::NwkAlternKeyInfo => 59,
            NvItemId::RouterOffAssocCleanup => 60,
            NvItemId::NwkLeaveReqAllowed => 61,
            NvItemId::NwkChildAgeEnable => 62,
            NvItemId::DeviceListKaTimeout => 63,
            NvItemId::BindingTable => 65,
            NvItemId::GroupTable => 66,
            NvItemId::ApsFrameRetries => 67,
            NvItemId::ApsAckWaitDuration => 68,
            NvItemId::ApsAckWaitMultiplier => 69,
            NvItemId::BindingTime => 70,
            NvItemId::ApsUseExtPanid => 71,
            NvItemId::ApsUseInsecureJoin => 72,
            NvItemId::CommissionedNwkAddr => 73,
            NvItemId::ApsNonmemberRadius => 75,
            NvItemId::ApsLinkKeyTable => 76,
            NvItemId::ApsDuprejTimeoutInc => 77,
            NvItemId::ApsDuprejTimeoutCount => 78,
            NvItemId::ApsDuprejTableSize => 79,
            NvItemId::DiagnosticStats => 80,
            NvItemId::BdbNodeIsonaNetwork => 85,
            NvItemId::SecurityLevel => 97,
            NvItemId::PreCfgKey => 98,
            NvItemId::PrecfgkeysEnable => 99,
            NvItemId::SecurityMode => 100,
            NvItemId::SecurePermitJoin => 101,
            NvItemId::ApsLinkKeyType => 102,
            NvItemId::ApsAllowR19Security => 103,
            NvItemId::ImplicitCertificate => 105,
            NvItemId::DevicePrivateKey => 106,
            NvItemId::CaPublicKey => 107,
            NvItemId::KeMaxDevices => 108,
            NvItemId::UseDefaultTclk => 109,
            NvItemId::RngCounter => 111,
            NvItemId::RandomSeed => 112,
            NvItemId::TrustcenterAddr => 113,
            NvItemId::LegacyNwkSecMaterialTableStart => 117,
            NvItemId::ExNwkSecMaterialTable => 7,
            NvItemId::UserDesc => 129,
            NvItemId::NwkKey => 130,
            NvItemId::PanId => 131,
            NvItemId::ChanList => 132,
            NvItemId::LeaveCtrl => 133,
            NvItemId::ScanDuration => 134,
            NvItemId::LogicalType => 135,
            NvItemId::NwkmgrMinTx => 136,
            NvItemId::NwkmgrAddr => 137,
            NvItemId::ZdoDirectCb => 143,
            NvItemId::SceneTable => 145,
            NvItemId::MinFreeNwkAddr => 146,
            NvItemId::MaxFreeNwkAddr => 147,
            NvItemId::MinFreeGrpId => 148,
            NvItemId::MaxFreeGrpId => 149,
            NvItemId::MinGrpIds => 150,
            NvItemId::MaxGrpIds => 151,
            NvItemId::OtaBlockReqDelay => 152,
            NvItemId::SapiEndpoint => 161,
            NvItemId::SasShortAddr => 177,
            NvItemId::SasExtPanid => 178,
            NvItemId::SasPanid => 179,
            NvItemId::SasChannelMask => 180,
            NvItemId::SasProtocolVer => 181,
            NvItemId::SasStackProfile => 182,
            NvItemId::SasStartupCtrl => 183,
            NvItemId::SasTcAddr => 193,
            NvItemId::SasTcMasterKey => 194,
            NvItemId::SasNwkKey => 195,
            NvItemId::SasUseInsecJoin => 196,
            NvItemId::SasPrecfgLinkKey => 197,
            NvItemId::SasNwkKeySeqNum => 198,
            NvItemId::SasNwkKeyType => 199,
            NvItemId::SasNwkMgrAddr => 200,
            NvItemId::SasCurrTcMasterKey => 209,
            NvItemId::SasCurrNwkKey => 210,
            NvItemId::SasCurrPrecfgLinkKey => 211,
            NvItemId::TclkSeed => 257,
            NvItemId::LegacyTclkTableStart12 => 257,
            NvItemId::LegacyTclkTableStart => 273,
            NvItemId::ExTclkTable => 4,
            NvItemId::ApsLinkKeyDataStart => 513,
            NvItemId::ApsLinkKeyDataEnd => 767,
            NvItemId::DuplicateBindingTable => 768,
            NvItemId::DuplicateDeviceList => 769,
            NvItemId::DuplicateDeviceListKaTimeout => 770,
            NvItemId::ZnpHasConfiguredZstack1 => 3840,
            NvItemId::ZnpHasConfiguredZstack3 => 96,
            NvItemId::ZcdNvExApsKeyDataTable => 6,
            NvItemId::ZcdNvExAddrmgr => 1,
        }
    }
}
